.github/PULL_REQUEST_TEMPLATE.md
README.md
dependencies/graknlabs/dependencies.bzl

* Bump @graknlabs_protocol version
* Add a pull request template
* Add a README with badges

Upgrade protocol and add README

---

dependencies/graknlabs/dependencies.bzl

Upgrade deps such that CI is green again
Bump versions of `@graknlabs_grakn_core` and `@graknlabs_client_java` to latest `master`

Upgrade dependencies

---

WORKSPACE
dependencies/graknlabs/dependencies.bzl
printer/StringPrinter.java
test/GraknConsoleIT.java

To match changes in https://github.com/graknlabs/grakn/pull/5667 and  https://github.com/graknlabs/client-java/pull/86, console also is updated to reflect the fact that roles can be duplicated.
* Bump cyclic dependencies
* Change a Set of Roles to a List of Roles in the printer

Disable role Put behavior

---

dependencies/graknlabs/dependencies.bzl

Remove temporary dependencies on forks of graknlabs repositories.
* Bump grakn core
* remove client-java fork dependency

Remove flyingsilverfin deps

---

config/logback/logback.xml

We accidentally enabled logging at the info level.
Turned logging off.

Turn logging off again

---

.circleci/config.yml
dependencies/graknlabs/dependencies.bzl

Update CI image to Ubuntu 16 and bump build tools

Update CI image to Ubuntu 16 and bump build tools

---

dependencies/graknlabs/dependencies.bzl

Fix CI by updating client-java

Fix CI by updating client-java

---

.circleci/config.yml
.gitignore
BUILD
dependencies/graknlabs/dependencies.bzl

We refined distribution rules and renamed them to `artifact` rules.
- Changes for `artifact` rules

Update to new artifact rules

---

GraknConsole.java

Add history file support. Two levels of REPL will use two different files. `~/.grakn-console-history` and `~/.grakn-console-transaction-history`.

Add history file support for new console

---

GraknConsole.java
Printer.java

Add syntax highlighting for the query result returned by the client java.

Add syntax highlighting to the result concept maps

---

.grabl/automation.yml
BUILD
GraknConsole.java
conf/logback/BUILD
conf/rpm/BUILD
conf/rpm/grakn-console.spec
dependencies/graknlabs/BUILD
dependencies/graknlabs/artifacts.bzl
dependencies/graknlabs/repositories.bzl
dependencies/maven/BUILD
templates/BUILD

Update client java and fix grabl CI.

Update client java

---

README.md
command/ReplCommand.java
command/TransactionReplCommand.java

Add console documentation to readme. Also slightly adjust the order and description of the console menu.

Add readme as console documentation

---

GraknConsole.java
dependencies/graknlabs/artifacts.bzl
dependencies/graknlabs/repositories.bzl

We have upgraded client java and enabled match query

Enable match query

---

GraknConsole.java

Currently the code that prints the answer doesn't always use `printCancellableResult`. We unify the code so that they always use `printCancellableResult`.

Unify the code used for printing answer

---

BUILD
common/Printer.java

Fix the issue when the variables displayed without the `$` sign and roles without the `scope` part in the query results in the console. 
Old query results
```
{ role type activated-protein sub role; x type protein-protein-interaction sub relation; }
{ role type associated-organism sub role; x type organism-association sub relation; }
{ role type modulated sub role; x type modulation sub relation; }
{ role type discovered-virus sub role; x type discovery sub relation; }
{ role type associated-virus sub role; x type protein-virus-association sub relation; }
{ role type associated-gene sub role; x type gene-disease-association sub relation; }
{ role type transcribing-gene sub role; x type transcription sub relation; }
{ role type associated-class sub role; x type disease-class-association …
```

Fix incorrect UI for roles and variables names

---

GraknConsole.java
README.md
command/ReplCommand.java
command/TransactionReplCommand.java

Allow running console in non-interactive mode, which accepts a script file containing a list of commands to run.
- Make console scriptable

Make console scriptable

---

GraknConsole.java
README.md

Allow having a list of commands specified in the command line, without using script file.
- Allow having a list of commands specified in the command line, without using script.

Allow specifying commands from command line without using script

---

dependencies/graknlabs/artifacts.bzl
dependencies/graknlabs/repositories.bzl

We updated Client Java and the Grakn Core artifact due to a new protocol.
Update Client Java and Grakn Core artifact

Update Client Java and Grakn Core artifact

---

BUILD
dependencies/graknlabs/repositories.bzl
dependencies/maven/artifacts.bzl
dependencies/maven/artifacts.snapshot

Allow printing colored text when running under Windows.
Add a dependency on `jline-terminal-jansi` such that text under Windows is properly colored.
Fix #134

Fix printing colored test under Windows

---

TypeDBConsole.java
command/REPLCommand.java
common/Utils.java

We now force passwords to be entered in a password prompt. This prevents passwords from showing up in the command history.
We've changed the flow of the user create command. Now, when creating a user, you supply a username and are then prompted to supply a password separately.

Mandate password prompt for user creation

---

TypeDBConsole.java
command/REPLCommand.java

We've added the ability to update user passwords through TypeDB Console.
This can be done with the syntax: `user password <username>` The user is then prompted to input a new password.
We've added a `REPLCommand` subclass `Password` that contains the necessary information to update a user's password.

Allow updating of user passwords

---

BUILD
TypeDBConsole.java
dependencies/vaticle/artifacts.bzl
dependencies/vaticle/repositories.bzl

We update the dependencies for the 2.17.0 release and print out each user's approximate password expiry time when listing users. 
* Update dependencies to the 2.17.1 client-java release
* Update user listing to include password expiry

Update dependencies for 2.17.0 release

---

.circleci/config.yml
.circleci/windows/deploy_release.bat

We set the Bazel compilation mode for releases to `opt`.

Set release compilation mode to optimized

---

TypeDBConsole.java
WORKSPACE
common/Printer.java
common/exception/ErrorMessage.java
dependencies/maven/artifacts.snapshot
dependencies/vaticle/repositories.bzl

We update to the newest version of TypeDB Driver which supports Fetch queries.
For more details on fetch queries, see https://github.com/vaticle/typeql/pull/300

Implement Fetch query

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/PULL_REQUEST_TEMPLATE.md
BUILD
TypeDBConsole.java
dependencies/maven/artifacts.bzl
dependencies/maven/artifacts.snapshot
dependencies/vaticle/repositories.bzl

We implement completely anonymous error reporting using Sentry. We submit error messages when the user receives a fatal error in Console.
To disable diagnostics, use:
```
typedb console --diagnostics-disable=true
```

Implement error diagnostics

---

.factory/automation.yml

Update factory owners to typedb

Update factory owners to typedb

---

src/main.rs
src/operations.rs

Add `user list` command to display the list of users existing on the server.

Add `user list` command

---

Cargo.lock
Cargo.toml

Update Cargo.toml for release 3.2.0-rc2

---

src/main.rs

We generate specific error codes to check when executing commands and scripts programmatically.
We now have the following exit codes:
```
Success = 0,
GeneralError = 1,
CommandError = 2,
ConnectionError = 3,
UserInputError = 4,
QueryError = 5,
```

Create specific exit error codes
