- config/rpm/grakn-console.spec
Fix assembly of `grakn-console` RPM package
Remove Grakn Console archive after unpacking (which is now enforced by `rpmbuild`)
> Fix building of RPM package

- .circleci/config.yml
We have added a validation step using `//ci:release-validate-deps` in order to ensure that console is releasable only if it depends on released versions of common, console, graql, protocol , and client-java.
> Use release-validate-deps to ensure that Console depends on released versions of common, console, graql, protocol , and client-java

- dependencies/graknlabs/dependencies.bzl
Make client-java 1.0.1 releasable by depending on released common `0.2.0`, graql `1.0.3`, protocol `1.0.2`. client-java is already set to the correct version which is `1.5.5` and there is no need to update them here.
> Make console 1.0.1 releasable by depending on released dependencies

- BUILD
Console had a remaining dependency on Grakn Core's implementation of Concept - this has been removed. 
All Grakn core clients should continue to use only Grakn Clients' implementations of Concepts.
> Remove Grakn Core Concept dependency

- dependencies/graknlabs/dependencies.bzl
- We've updated `graql`, `common` and `protocol` which are depended by `client-java`.
> Prepare for a release by updating graknlabs_graql, graknlabs_common and graknlabs_protocol to release versions

- .circleci/config.yml
- BUILD
- ConsoleSession.java
- GraknConsole.java
- WORKSPACE
- config/logback/BUILD
- config/logback/logback.xml
- config/rpm/BUILD
- dependencies/graknlabs/BUILD
- dependencies/graknlabs/dependencies.bzl
- dependencies/maven/BUILD
- dependencies/maven/dependencies.yaml
- dependencies/maven/update.sh
- deployment.properties
- exception/ErrorMessage.java
- exception/GraknConsoleException.java
- printer/Printer.java
- printer/StringPrinter.java
- templates/BUILD
- templates/Version.java
- test/BUILD
- test/GraknConsoleIT.java
- test/resources/BUILD
- test/resources/grakn.properties
In order for build not to break after graknlabs/build-tools#122, copyright headers need to be updated.
Update copyright headers to match new format
> Update copyright headers to 2020

- ConsoleSession.java
- exception/GraknConsoleException.java
- test/BUILD
- test/GraknConsoleIT.java
List, Delete existing keyspaces from console. Previously we had to spin up an interactive python console or something similar to see what keyspaces even exist in a distribution, let alone delete them.
To access the new commands, we would run in any console session:
```
grakn> keyspace list
```
which should print the list of keyspaces on the grakn distribution the console is connected to.
Similarly, we can do:
```
grakn> keyspace delete somekeyspace
Successfully deleted somekeyspace
```
* Add `keyspace list` and `keyspace delete [keyspace]` as a commands in console
* Add test for `keyspace list` and `delete`
> Add ability to list and delete keyspaces from console

- dependencies/graknlabs/dependencies.bzl
- test/BUILD
- test/GraknConsoleIT.java
- test/invalid-data.gql
https://github.com/graknlabs/grakn/issues/5043 as a part of refactoring test packages in core, we move one `end-to-end test` into console as it should not have been tested in core.
Bump dependencies of core, protocol, client-java, build-tools. Significant change includes using `value` instead of `datatype`.
* Migrate one test from grakn core
* Switch tests to use `value` instead of `datatype`
> Migrate load relative path file in and bump deps

- ConsoleSession.java
- dependencies/graknlabs/dependencies.bzl
- test/BUILD
- test/GraknConsoleIT.java
We upgrade console to use the latest grakn core and client-java dependencies, resolving their own build issues induced by circular dependencies.
* Bump client-java to one of the latest version
* Bump grakn-core to the latest master
* Bump protocol to newest protocol
* Bump graql to newest commit
> Update to 1.8 dependencies

- BUILD
Starting console from April 2020 onwards resulted in verbose startup logging. This was due to an extra logback file being included in the JAR, which we remove again.
* Remove logback from the JAR, resulting in no duplicate logback and therefore no error messages on console bootup.
> Remove extra logback inclusion

- .circleci/config.yml
- .gitignore
- BUILD
- deployment.properties
Grakn core depends on console in order to create an "all" release package, however, it currently builds console from source (via bazel) which means we have two "releases" of console, one in this repo and one in the `grakn` repo, and they can have different sets of dependencies. This could cause any number of problems, not least being that tests run in this repo do not necessarily reflect the correctness of console in `grakn`. It also causes problems for us locally when using bazel to develop locally, because external workspaces imported in our own repo can leak into console unintended.
In order to fix this "artifact drift" we need to move to a "single true artifact" pattern. Currently, this artifact will only be `console-deps`, which does not include configuration (only `logback.xml` …
> Add console-deps deployment to repo as archive

- .circleci/config.yml
- BUILD
- WORKSPACE
- dependencies/graknlabs/artifacts.bzl
- dependencies/graknlabs/repositories.bzl
- deployment.bzl
Update to use cleaned up assemble-maven, deployment targets, and new format of deployment properties in `deployment.bzl`.
> Refactor: clean up to use 2.0 build dependencies

- GraknConsole.java
- ReplCommand.java
- TransactionReplCommand.java
- Utils.java
Make ctrl-c possible to escape from the REPL loop.
- ctrl-c on the first level of REPL will exit the console
- ctrl-c on the second level of REPL will go back to the first level
- In both cases, when there are already input, it will just cancel the input without cancel the REPL loop.
This solution is **NOT** perfect, since now with a long running query, ctrl-c will kill the entire console. To properly handle that, we need to register signal handler and there will be more work related to it.
- Make `getCommand` call throws `InterruptedException` when the user interrupts with `ctrl-c`.
> Make ctrl-c possible to break out of REPL loop

- GraknConsole.java
Make **only** the result streaming query cancellable, all other operations will ignore interrupts.
Install a signal handler to set `isCancelled` to true on ctrl-c interrupt so that we will break out iterating over the concept map stream.
> Make stream result iteration cancellable

- dependencies/graknlabs/repositories.bzl
In order to get `console` back to buildable state, we should revert repository dependencies back to those that are available to fetch - which is latest `master` of all of them.
Depend on latest `master` of `dependencies`, `common` and `client-java`
> Revert all dependencies back to latest commits

- .grabl/automation.yml
Currently, we depend on commits of `common` and `client-java` which makes `dependency-analysis` fail.
Allow us to depend on commits of `common` and `client-java`
> Allow commit dependencies on common and client-java

- .bazelrc
- .grabl/automation.yml
- dependencies/graknlabs/repositories.bzl
In order to speed up our builds, we should do them remotely on BuildBuddy
Tweak `.bazelrc` settings to build on BuildBuddy with our own Ubuntu 20.04 image
> Build remotely on Ubuntu 20.04

- .bazelrc
- .gitignore
- .grabl/automation.yml
- BUILD
- GraknConsole.java
- WORKSPACE
- command/ReplCommand.java
- command/TransactionReplCommand.java
- common/Printer.java
- common/Utils.java
- conf/logback/BUILD
- conf/logback/logback.xml
- conf/rpm/BUILD
- conf/rpm/grakn-console.spec
- dependencies/graknlabs/BUILD
- dependencies/graknlabs/artifacts.bzl
- dependencies/graknlabs/repositories.bzl
- dependencies/maven/BUILD
- dependencies/maven/artifacts.bzl
- dependencies/maven/update.sh
- deployment.bzl
- templates/BUILD
- templates/Version.java
License headers are currently out of date (2020) for a while. This PR replaces 2020 with 2021 across all the files.
* Replace `2020` with `2021` in source files
> Bump year in license headers to 2021

- dependencies/graknlabs/repositories.bzl
We have fixed an issue that caused console to exit when trying to open transaction to a database that doesn't exist.
- Bump client-java to the version which no longer throws the incorrect exception, causing console to exit improperly
- Fix https://github.com/graknlabs/console/issues/98
> Fix console exitting when trying to open transaction to a database that doesn't exist

- command/ReplCommand.java
- command/TransactionReplCommand.java
- common/Utils.java
Allow user to paste multiline input to console and edit as one unit.
- Set continuation prompt to be empty indentation.
- Set history of multiline query as one single unit.
- Fix https://github.com/graknlabs/console/issues/99
> Allow pasting multiline input

- .grabl/automation.yml
- GraknConsole.java
- common/Printer.java
- conf/logback/logback.xml
- dependencies/graknlabs/repositories.bzl
We have added Grakn Cluster support. A user can connect to a cluster of Grakn Cluster instances using the `--cluster` flag:
```
./grakn console --cluster 172.0.01:1729
```
- Adds a new flag `--cluster` for connecting to Grakn Cluster
- Update client-java to the version which supports cluster
> Add Grakn Cluster support

- dependencies/graknlabs/artifacts.bzl
- dependencies/graknlabs/repositories.bzl
- dependencies/maven/artifacts.snapshot
Fix `WARNING: An illegal reflective access operation has occurred` warning caused by an out of date version of protobuf.
- Update protobuf to latest.
> Fix console warnings caused by out of date dependency

- BUILD
Make Grakn Console distributions for Windows operational by adding previously lacking `grakn.bat` (a Windows-specific script to start the Console).
Correctly include Bat script if Console is being assembled for Windows
> Fix Grakn Console distribution for Windows

- GraknConsole.java
Previously, running `database list` with no databases present on the server gave no output and was difficult to distinguish from the console hanging or the server otherwise failing to respond. We added a more explicit response when no database is present on the server to make it clearer when this case has occurred.
- `database list` with no databases present now prints `No databases are present on the server.` instead of nothing at all.
> When no databases are present, say as much on database list

- GraknConsole.java
Fix two issues in the console. First, we properly shutdown the console when users type `exit` command in both levels of the REPL. Second, when a transaction is errored, we properly return from the transaction REPL as the transaction has been closed and not usable anymore.
- Call `executorService.shutdown();` on `exit` command. Fix https://github.com/graknlabs/console/issues/118
- Throw exceptions from query jobs to the main thread so that the transaction is properly closed. Fix https://github.com/graknlabs/console/issues/119
> Fix console not able to shutdown on exit and not close errored transaction

- .grabl/automation.yml
- BUILD
Always deploy artifacts bundled together with a shell startup script. 
- Deploy shell script together with artifact.
- Rename `tgz` to `tar.gz` to be more consistent with server.
> Always deploy artifacts bundled together with a shell startup script

- GraknConsole.java
- command/ReplCommand.java
- common/Printer.java
- dependencies/graknlabs/repositories.bzl
We added the 'database replicas' command for Grakn Cluster, which lists information about the replicas of a specified database. It includes: the network address of each replica, its role (primary/secondary), and the term of the most recent election it took part in.
Add 'database replicas' command
> Add 'database replicas' command

- GraknConsole.java
- command/ReplCommand.java
- dependencies/graknlabs/repositories.bzl
We added the `--any-replica` flag when opening a transaction in Cluster. When `--any-replica` is set, the transaction may read from any database replica, including secondary replicas.
- Add option to read from any replica in Cluster
- When connecting to Grakn Core, the `help` command now only shows commands (and flags) that can be used in Core
> Add option to read from any replica in Cluster

- BUILD
- GraknConsole.java
- command/ReplCommand.java
- common/exception/GraknConsoleException.java
- dependencies/graknlabs/artifacts.bzl
- dependencies/graknlabs/repositories.bzl
Allow console users to set any transaction options they like, by introducing `Options` that can be provided as `--flag` when opening a transaction. This will simplify debugging (especially for reasoner), and allow us to experiment with parallel/not parallel, along with all other available options.
* Create `Options` class with two inner classes - `Core` and `Cluster`
* Also create `Options.Options`, which handles parsing values from the command line
* Options also have help menus, etc, as expected.
> Introduce transaction options

- command/ReplCommand.java
Fix null pointer in transaction options that occurs because the option builder is not saved.
* save builder to field
> Actually save transaction option parameters to fields

- GraknConsole.java
Previously when closing a READ transaction, it would print "Transaction closed without committing changes". "Without committing changes" was superfluous so we got rid of it.
When closing a READ transaction, simply print "transaction closed"
> When closing a READ transaction, simply print "transaction closed"

- BUILD
- dependencies/graknlabs/repositories.bzl
Improve consistency of Grakn Console distribution and help fix an issue with long filenames in the assembled archives for Grakn Cluster.
Depends on graknlabs/common#100
Move console libraries into `console/lib/`
> Tweak location of console libraries

- README.md
- command/ReplCommand.java
The `database schema` command, implemented in https://github.com/graknlabs/console/pull/143, was missing from the `help` command and the `README` file. We added it to both.
Add 'database schema' to help command and README
> Add 'database schema' to help command and README

- GraknConsole.java
- command/TransactionReplCommand.java
- common/exception/ErrorMessage.java
To make the error in https://github.com/graknlabs/console/issues/139 much cleaner, we implement a check for the required number of space-separated arguments. An incorrect number of arguments is no longer a fatal error.
* Transaction-level REPL check required number of argument, and fail gracefully otherwise
* mis-used transaction repl errors no longer kill the console
> Transaction REPL checks arguments

- TypeDBConsole.java
- command/ReplCommand.java
- dependencies/vaticle/repositories.bzl
We have added authentication and user management support for to TypeDB Cluster.
- Added `--username` and `--password` options. The options are validated such that they can only be supplied when connecting to TypeDB Cluster (it doesn't make sense to supply them when connecting to TypeDB which doesn't support authentication).
- Added the user management feature allowing users to manage user credentials:
- `user create user1`
- `user list`
- `user delete user1`
> Add authentication and user management support for TypeDB Cluster

- TypeDBConsole.java
- command/REPLCommand.java
- command/TransactionREPLCommand.java
- common/Utils.java
- common/exception/ErrorMessage.java
- dependencies/maven/artifacts.snapshot
- dependencies/vaticle/repositories.bzl
We've updated Console such that password input can be supplied interactively and non-interactively.
This is done primarily for security purpose, interactive input will be the preferred one since it is not stored in the CLI history. The non-interactive mode is still relevant and therefore supported, particularly for use in automation scripts and test.
Additionally, we've refactored the code to improve the terminologies. We used the word "Command" everywhere to refer to several different things which cause confusion. We've now made the terminologies more precise:
- "CLI Options" is how we refer to the options specified when starting console (eg., `--username admin`)
- "REPL command" is how we refer to the Console commands such as 'database create'
- We've renamed the execution mode to be …
> Improve handling password input

- BUILD
Depend on Java 11 in APT package for consistency with TypeDB Server
Depend on `openjdk-11-jre` for APT installations.
> Upgrade Java dependency for APT package

- .grabl/automation.yml
- dependencies/vaticle/repositories.bzl
Make APT package that we deploy installable again
Use Python 3.7 version to run `deploy-apt-*` jobs to avoid bazelbuild/rules_pkg#397
> Fix APT package deployment

- TypeDBConsole.java
- command/REPLCommand.java
Introduce context-aware autocomplete for interactive TypeDB Console sessions. 
Fix #172
* Make all commands' `token`s public so they can be reused when instantiating completer classes
* Instantiate a completer using `TreeCompleter` class from JLine. It's aware of context: where database name is expected, it completes database names; same is true for user names in `user delete <username>` command.
> Autocomplete for commands

- TypeDBConsole.java
- command/TransactionREPLCommand.java
- common/exception/ErrorMessage.java
We make the `source` command not use the pretty-printer or wait for results unless specified with the `--print-answers` flag, which is optional.
* `source` now has an optional `--print-answers`
* when not printing answers, we execute all the queries in the query string as async queries, then wait for them all at the end
* define/undefine never are fully async, and ways do a get() on the query result.
> Source command is quiet by default

- RunQueriesResult.java
- TypeDBConsole.java
We've added an indicator for uncommitted changes within a transaction. While you are in a transaction that has uncommitted changes, an asterisk (*) will now be displayed in the prompt.
Also, concept deletion is now more transparent; the number of concepts being deleted (or updated) is printed to the console now. This is particularly helpful for catching when there is a bug in the match query that might cause it to delete no concepts, or the wrong concepts.
- Indicate uncommitted changes
- Print the number of concepts that are being deleted (or updated)
We chose to not add a confirmation prompt prior to deletion just yet, this is due to Console architecture making that too difficult for now. This is (still!) tracked in:
- #166
> UX improvements to transaction commits and concept deletion

- TypeDBConsole.java
We've added support for TypeQL-style comments in scripts. So, for example, you can now pass the following file to `--script`:
```
database create social_network
transaction social_network schema write
source social_network_schema.tql
commit
```
- Fix pluralisation when deleting concepts
- Allow TQL-style comments in scripts (fixes #170)
> Allow TypeQL-style comments in scripts

- .bazelrc
- .gitignore
- .grabl/automation.yml
- BUILD
- RunQueriesResult.java
- TypeDBConsole.java
- WORKSPACE
- command/REPLCommand.java
- command/TransactionREPLCommand.java
- common/Printer.java
- common/Utils.java
- common/exception/ErrorMessage.java
- common/exception/TypeDBConsoleException.java
- conf/logback/BUILD
- conf/logback/logback.xml
- dependencies/maven/BUILD
- dependencies/maven/artifacts.bzl
- dependencies/maven/update.sh
- dependencies/vaticle/BUILD
- dependencies/vaticle/artifacts.bzl
- dependencies/vaticle/repositories.bzl
- deployment.bzl
- templates/BUILD
- templates/Version.java
We update the copyright header year to 2022.
Bump the vaticle-dependencies commit & replace the year 2021 with 2022 in each copyright header.
> Bump copyright year to 2022

- .grabl/automation.yml
- BUILD
- LICENSE
- WORKSPACE
- conf/logback/BUILD
- dependencies/maven/BUILD
- dependencies/vaticle/BUILD
- dependencies/vaticle/repositories.bzl
- templates/BUILD
We update the copyright header year to 2022, and introduce a test that ensures that the license text is correct.
* Bring all the `checkstyle_test()` invocations in line with the updated definition in dependencies;
* Replace all references to `typeql-lang-java` with `typeql/java`;
* Use checkstyle to confirm that the license text is correct.
> Extend license checkstyle tests and update licenses

- TypeDBConsole.java
JLine line parser, which handles console's REPL, no longer swallows backslahes and other escape characters. 
Previously, this lead to unexpected behaviour:
```
tmp::data::write> insert $x "hello \" world" isa val;
[TQL03] TypeQL Error: There is a syntax error at line 1:
insert $x "hello " world" isa val;
^
mismatched input 'world' expecting {';', 'has'}
```
Now, JLine keeps all the escape characters in place and hands the query parsing to TypeQL:
```
tmp::data::write> insert $x "hello \" world" isa val;
{ $x "hello \" world" isa val; }
```
* Replace the set of escape characters that JLine swallows with an empty set
> Disable Jline backslash stripping

- TypeDBConsole.java
- dependencies/vaticle/repositories.bzl
Console now quits upon a user changing their own password, rather than having a user be left in a session with invalid credentials (which they will only discover on running subsequent commands).
Fixes: #200 
We've added checks to determine whether password sets and updates were successful, and if so, prompt the user to log in again before quitting.
> Prompt a re-login when users change their own passwords

- TypeDBConsole.java
We've changed the wording and logic of the password expiry warning to be more accurate.
This brings us in line with our implementation in Studio: https://github.com/vaticle/typedb-studio/pull/722
To avoid returning "[...] will expire in 0 hours.", we now return "[...] will expire within 1 hour(s)." This is accurate and less jarring for users.
> Change wording of password expiry warning

- common/Printer.java
- dependencies/vaticle/repositories.bzl
We allow users to interact via Console with the new Value API introduced in https://github.com/vaticle/typeql/pull/260. This PR adds pretty printing for value concepts and updates required dependencies to support the change.
* Update to a client-java version that supports Values in queries and answers
* Update the concept pretty-printer to allow printing Value concepts. 
* Update ConceptMap printing to first print concept variables (`$`) by alphabetical sorting of the variable name, and then value variables (`?`) by alphabetical sorting.
> Introduce computed values

- BUILD
- README.md
- TypeDBConsole.java
- WORKSPACE
- command/REPLCommand.java
- common/Printer.java
- dependencies/vaticle/repositories.bzl
We replace the term 'cluster' with 'enterprise', to reflect the new consistent terminology used through Vaticle. We also replace 'client' with 'driver', where appropriate.
* Update REPL, README and code to no longer refer to TypeDB 'Clients', and use the new terminology of TypeDB 'Drivers', and replace usage of TypeDB 'Cluster' with TypeDB 'Enterprise'
> Replace usages of 'client' and 'cluster' with 'driver' and 'enterprise' throughout

- .circleci/config.yml
- BUILD
`apt` expects the architecture tag for x86_64 to be `amd64`.
> Deploy apt amd64 with correct architecture tag

- README.md
- TypeDBConsole.java
- dependencies/vaticle/repositories.bzl
- test/assembly/AssemblyTest.java
We update the CLI options to use the more distinct `--core` flag for connecting to the core server, mirroring `--enterprise`.
Connecting to TypeDB Core:
```
typedb console --core=<address>
```
Connecting to TypeDB Enterprise (unchanged):
```
typedb console --enterprise=<address> --username=<username> --password --tls-enabled
```
See https://github.com/vaticle/typedb/issues/6942 for full details.
We also improve the UX of the windows version of the entry point. Console no longer opens in a new window, but rather begins the REPL in the current command line window.
> Update command line interface

- README.md
- TypeDBConsole.java
- command/REPLCommand.java
- dependencies/vaticle/repositories.bzl
We replace the term 'enterprise' with 'cloud', to reflect the new consistent terminology used throughout Vaticle. In particular, this means that to connect to a Cloud instance (previously Enterprise), `typedb console --cloud <address>` replaces `typedb console --enterprise <address>`.
> Replace all instances of 'enterprise' with 'cloud'

- .bazelrc
- .circleci/config.yml
- .circleci/windows/dependencies.config
- .circleci/windows/prepare.bat
We compile and release TypeDB Console using an older version of Linux, which requires GLIBC 2.26 instead of GLIBC 2.27. This change switches the build platform to Amazon Linux 2 (via Docker), which is based on CentOS, instead of Ubuntu 18.04, which is based on Debian.
Additionally, we upgrade the Windows Orb to 5.0.0, which also allowed using a larger executor to reduce CI time.
- Migrate to `amazonlinux:2` docker for Linux builds
- We migrate package installation and dependency management for build steps to use `yum`/`rpm` package management
- Migrate windows orb to `5.0.0`, and set executor to 'large'
- We update the Python and VC installation parameters as required
> Reconfigure CircleCI executors

- .factory/automation.yml
- tool/runner/BUILD
- tool/runner/TypeDBConsoleRunner.java
We remove `typedb-console-runner`'s dependency on common in order to reduce deployment complexity and make the maven library self-contained.
> Remove typedb-console-runner's dependency on typedb-common

- .circleci/config.yml
- .circleci/windows/deploy_release.bat
- .circleci/windows/deploy_snapshot.bat
- .factory/automation.yml
- BUILD
- WORKSPACE
- dependencies/maven/artifacts.snapshot
- dependencies/vaticle/artifacts.bzl
- dependencies/vaticle/repositories.bzl
- tool/runner/BUILD
Updates artifact credentials, and deployment & consumption rules to use cloudsmith (repo.typedb.com) instead of the self-hosted sonatype repository (repo.vaticle.com).
* Updates deployment & artifact consumption rules to point to Cloudsmith and update deployment rules and repositories
* Updates artifact_groups to reflect the revised repository layout
* Update package import paths for TypeDBRunner
> Migrate artifact hosting to cloudsmith

- tool/runner/TypeDBConsoleRunner.java
Makes TypeDB console runner use the  same java installation as the calling process, so the system remain hermetic. 
* Sets `JAVA_HOME` for the console subprocess to the `java.home` system property of the host process.
> Make console runner use the same java installation as the calling process

- .circleci/config.yml
- .factory/automation.yml
We add a sync-dependencies job to be run in CI after successful snapshot and release deployments. The job sends a request to vaticle-bot to update all downstream dependencies.
Note: this PR does _not_ update the `dependencies` repo dependency. It will be updated automatically by the bot during its first pass.
> Sync dependencies in CI

- BUILD
- WORKSPACE
Since the upgrade to rules-python v0.24 (https://github.com/vaticle/dependencies/pull/460), we are required to explicitly install python dependencies in the WORKSPACE file. The python tools happened to be unused, so these errors were not visible until the sync dependencies tool was restored.
> Explicitly install python tool dependencies

- .circleci/config.yml
- .circleci/windows/deploy_release.bat
- .factory/automation.yml
- BUILD
- RELEASE_TEMPLATE.md
- WORKSPACE
- dependencies/vaticle/repositories.bzl
We update Bazel dependencies and target paths following the merging of typedb-common into [vaticle/typeql](https://github.com/vaticle/typeql/) (see https://github.com/vaticle/typeql/pull/313).
We also no longer upload build artifacts to the github releases page. Instead, the artifacts are available from our public cloudsmith repository, linked in the release notes.
- update ghr to 0.16.2, as 0.12.1 does not support github releases without artifacts
> Use typedb-common from typeql/common, only deploy to CloudSmith

- .circleci/config.yml
The sync-dependencies step in CircleCI used an obsolete setup step which no longer exists. This PR fixes that issue.
> Fix sync-dependencies job in CircleCI

- .circleci/windows/short_workspace.patch
We update the git patch used for workspace path shortening in Windows CI builds.
> Fix git patch for Windows build

- test/assembly/AssemblyTest.java
We turn off the `--diagnostics.reporting.statistics` in our CI builds not to send non-real diagnostics data.
In version 2.28 and earlier, this flag purely prevents `TypeDB` from sending any diagnostics data.
In the upcoming version 2.28.1, this flag still allows `TypeDB` to send a single diagnostics snapshot with the information of when the diagnostics data has been turned off, but it happens only after the server runs for 1 hour, so we expect the CI builds not to reach this point and not to send any diagnostics data as well.
> Turn off statistics reporting in CI

- .circleci/config.yml
- dependencies/maven/artifacts.snapshot
- dependencies/vaticle/repositories.bzl
Bump dependencies for rules-python update. This fixes an error on windows builds in CircleCI.
We also pin the image used for Windows builds  on CircleCI to prevent updates from breaking the pipeline.
> Bump dependencies for rules-python & pin CircleCI windows executor

- TypeDBConsole.java
Removes a hard-coded value for transaction timeout, which prevented the user's setting from taking effect.
Removes a hard-coded value for transaction timeout, which prevented the user's setting from taking effect.
> Remove hard-coded value for transaction timeout

- .circleci/config.yml
Migrates the  CircleCI mac jobs to arm64 executors
Migrates the  CircleCI mac jobs to arm64 executors, ahead of the shut-down of x86_64 executors on June 28th. In jobs for x86_64 builds of Mac, we update the steps to:
* Install rosetta
* Install bazelisk for the specific architecture, passed via a parameter ``<<bazel.arch>>`
> Migrate CircleCI mac jobs to arm64 executors

- .factory/automation.yml
- BUILD
- README.md
- RunQueriesResult.java
- TypeDBConsole.java
- WORKSPACE
- command/REPLCommand.java
- common/Printer.java
- dependencies/maven/artifacts.snapshot
- dependencies/vaticle/repositories.bzl
- test/assembly/AssemblyTest.java
- test/assembly/BUILD
We refactor console to support the updated `typedb` of 3.0-alpha.
Non-existing features are deleted. Non-implemented features are commented out (cloud, user management, options). 
The new output looks like this: 
```
> database create its-my-pr
Database 'its-my-pr' created
> transaction its-my-pr schema
its-my-pr::schema> define
attribute name, value string;
entity person, owns name;
Success
its-my-pr::schema> commit
Transaction changes committed
> transaction its-my-pr write
its-my-pr::write> insert $x isa person, has name "John"; $y isa person, has name "Alice";
Finished validation and compilation...
Finished writes. Streaming answers...
---------
$x | iid 0x1e00000000000000000000 isa person
$y | iid 0x1e00000000000000000001 isa person
---------
Finished. Total answers: 1 …
```
> Refactor console for 3.0

- TypeDBConsole.java
We fix an issue that caused an error to be thrown by password update commands, in spite of them succeeding
We retrieve the current username before updating the password, so it no longer relies on the now deauthenticated connection.
> Fix error throwing on password update

- TypeDBConsole.java
- common/Printer.java
Enhance printing logic to handle two special cases of received answers:
* When a variable with no values is returned, an empty result will be shown instead of a crash (it used to be considered an impossible situation).
* When concept rows are returned, but they do not have any columns inside (possible for `delete` stages), a special message is written, and the number of answers (rows) is still presented.
The handling of optional vars is temporarily implemented through a `catch`. The interface should already return an Optional (for all drivers...): I wanted to implement it with optionals as I didn't know we could have empty vars right now. See examples below.
Read with row answers:
```
sample_db::write> match $u isa user;
Finished validation and compilation...
Streaming answers...
-------- …
```
> Fix printing of variables with empty values and rows with no columns

- common/Printer.java
- dependencies/typedb/repositories.bzl
Update the Driver dependency to work with optional concepts from rows.
Check the optional result and get its concept instead of a temporary `try {} catch` block.
> Update the Driver dependency to work with optional concepts from rows

- README.md
- src/cli.rs
- src/completions.rs
- src/main.rs
- src/operations.rs
- src/repl/command.rs
- src/repl/line_reader.rs
- src/repl/mod.rs
- tests/assembly/test_assembly.rs
We refactor the Console to allow pasting a "script" into the current REPL. This will be correctly interpreted and executed as a block of separate commands. The inputs must look as they would when using the console interactively:
```
database create tmp
transaction schema tmp
define entity person;
commit
```
With the empty newline, as in regular interactive console, being used to mark the end of the query.
This is particularly useful for pasting fully self-contained examples from TypeDB documentation into the console!
The format of `--file` scripts (now called `--script`) must follow this same format, instead of using `\` to write multiline queries. We will refer to this as the `TypeDB Console Script`, or `Scripted TypeQL` in some contexts. We use `.tqls` for console scripts, instead of …
> Multiline script paste and unified scripting format

- src/main.rs
- src/operations.rs
- src/repl/command.rs
- src/repl/line_reader.rs
- src/repl/mod.rs
We an important bug:
1.
```
>> match
$x isa person; |
```
2. navigate cursor and enter newlines
```
>> match
| $x isa person;
```
Various things would break, including submitting the "script" prematurely. Now, the block is only submitted when the sequence of commands entered are a valid script.
Additionally, the UX if Ctr+C is improved: when hitting Ctrl+C on a non-empty line, the line is retained, rather than cleared.
- hack around RustyLine to retain the previous line but not exit
- improve query/command submission logic
> Improve UX of Ctrl+C and fix bugs in command submission

- BUILD
- Cargo.lock
- Cargo.toml
- README.md
- WORKSPACE
- dependencies/typedb/repositories.bzl
- src/main.rs
- src/operations.rs
- src/repl/command.rs
We improve multi-line query support to allow copy-pasting queries and scripts containing empty newlines. In particular this makes pasting entire schema definitions from files. 
For example, pasting a console script opening a transaction, defining a schema containing newlines, and committing, is now possible:
```
>> transaction schema test
define 
entity person;  # newlines are allowed in pasted scripts:
attribute name, value string;
person owns name; 
commit
```
Empty newlines when written _interactively_ still cause queries to be submitted. However, an explicit query `end;` clause is a valid alternative now:
```
>> transaction schema test
define 
entity person;  # newlines are allowed in pasted scripts:
attribute name, value string;
person owns name; 
end; # <--- will submit immediately …
```
> Improve multiline query support

- src/constants.rs
- src/main.rs
- src/operations.rs
Set transaction timeout for opened transactions to 1 hour.
This change significantly lowers the impact of https://github.com/typedb/typedb-console/issues/287.
Use the new `transaction_with_options` interface of the Rust driver to pass configured transaction options.
> Increase transaction timeout

- src/cli.rs
- src/main.rs
- src/operations.rs
- src/repl/mod.rs
We support using relative paths for the `--script` command (relative to the current directory), as well as relative paths for the REPL `source` command.
When `source` is invoked _from_ a script, the sourced file is relativised to the script, rather than the current working directory.
* Store the console's working directory, and the script directory if a script is active (scripts can't be nested, which enables this!)
* Relativize to either the script directory or the working directory as when running with `--script` mode and `>> source <path>
` commands
> Support relative script and source commands

- Cargo.lock
- Cargo.toml
- dependencies/typedb/repositories.bzl
- src/main.rs
- src/operations.rs
- tool/runner/Cargo.toml
Add database export and database import operations. 
Database export saves the database information (its schema and data) on the client machine as two files at provided locations:
```
database export my-database export/my-database.typeql export/my-database.typedb
```
Database import uses the exported files to create a new database with equivalent schema and data:
```
database import their-database export/my-database.typeql export/my-database.typedb
```
Add new commands similar to other `database` interfaces. Prepare data to call the respective [typedb-driver APIs](https://github.com/typedb/typedb-driver/pull/758).
> Introduce database export and import

- Cargo.lock
- Cargo.toml
- dependencies/typedb/repositories.bzl
Support build on Apple Clang 17+ by updating dependencies (details: https://github.com/typedb/typedb-dependencies/pull/577).
> Update zlib dependency 

- BUILD
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/operations.rs
- src/repl/command.rs
- src/repl/mod.rs
We introduce a new command `database create-init`, which 
1) create the new database
2) loads a provided schema file (from URL, or from local file)
3) loads a provided data file (from URL or from local file)
Command format:
```
database create-init <db> <schema file> <data file> <[optional] schema file sha256 (hex or sha256:hex)> <[optional] data file sha256 (hex or sha256:hex)>
```
Usage example to load bookstore example from `typedb-examples`:
```
>> database create-init bookstore https://github.com/typedb/typedb-examples/releases/download/3.5.0/bookstore-schema.tql https://github.com/typedb/typedb-examples/releases/download/3.5.0/bookstore-data.tql
```
You can also optionally provide sha256 checksums to verify your files are correct (these come from the Github releases page):
```
>> …
```
> Introduce 'create-init' command to load a new database from schema/data
